### ISSUE TITLE
[BUG] Anticheat & spawn armi.

### ISSUE THREAD

**Issue by Rommel-theFox** [Lorenzo978/OC-issues#10]
**Descrizione**
Il bug consente di poter utilizzare armi spawnate con sobeit in concomitanza con armi prese in modo "lecito". Se si ha un'arma presa in maniera lecita e si spawna la stessa arma con sobeit, si aggiungeranno delle munizioni all'arma già detenuta (munizioni ovviamente ottenute con i cheat), se si mantiene sobeit attivo allora si potrà continuare a sparare nonostante l'anticheat cerchi di togliere le munizioni spawnate (perchè sobeit fissa le munizioni al valore che dice lui e non le fa scendere al di sotto di quel valore). Se però si disattiva sobeit, l'anticheat fa il suo giusto lavoro e porta l'arma alle munizioni lecite.
Se si rilogga però, l'arma scompare definitivamente perdendo tutte le munizioni, sia quelle lecite che quelle spawnate.

**Per riprodurlo**
I passaggi sono i seguenti:
- Prendere un'arma in maniera "lecita", quindi prenderla dall'inventario oppure con /giveweapon.
- Equipaggiare l'arma
- Spawnare LA STESSA ARMA con sobeit: adesso si potrà constatare quanto detto nella descrizione.
- Riloggare e constatare la perdita dell'arma, sia dei proiettili spawnati che quelli "leciti".

**Cosa dovrebbe fare**
L'arma dovrebbe essere subito switchata al pugno come nella issue [MOD] che ho scritto, allo stesso modo al relog l'arma dovrebbe tornare ai proiettili leciti e non essere persa definitivamente.

**Screenshots (opzionale)**
//

**Comment by Lorenzo978** [comment]
_Risolto **(probabilmente)** nella versione_ **0.4.1**
