### ISSUE TITLE
[BUG] Spas-12 & Inventario

### ISSUE THREAD

**Issue by Rommel-theFox** [Lorenzo978/OC-issues#14]
**Descrizione**
Attualmente lo Spas-12 non è gestito con l'inventario, infatti se si prova a raccogliere un fucile (di tipo shotgun) mentre si ha uno Spas-12 in mano, normalmente quest'ultimo dovrebbe finire nell'inventario ma in questo caso l'inventario scompare totalmente è non c'è possibilità di riaprirlo, neanche al relog.

**Per riprodurlo**
- Gettare uno shotgun o un sawn-off a terra.
- Givvarsi uno Spas-12.
- Raccogliere il sawn-off mentre si ha lo Spas-12 equipaggiato.
- Constatare che l'/inv scompare.

**Screenshots (opzionale)**
//

**Comment by Lorenzo978** [comment]
Normalmente in gioco nessun giocatore potrà avere in inventario uno Spas-12 (tranne il PD durante il servizio, ma in questo caso non è consentito l'accesso ad inventario) perciò è una situazione non gestita volutamente.
