### ISSUE TITLE
[BUG] Sistema armi.

### ISSUE THREAD

**Issue by Rommel-theFox** [Lorenzo978/OC-issues#4]
**Descrizione**
Se si ha un'arma in mano caricata con qualsiasi proiettile e si viene uccisi, una volta respawnati se si prova ad equipaggiare lo stesso tipo di arma uscirà un errore "Hai già un ARMA in mano."
Se si rilogga, l'arma che si aveva prima della morte (incluse le munizioni equipaggiate con quell'arma) ritorna in mano al giocatore.

**Per riprodurlo**
Spawnarsi un'arma, equipaggiarla, ammazzarsi e provare a riequipaggiare un'arma dello stesso tipo. Infine, riloggare e constatare che si ha in mano l'arma persa con la morte.

**Cosa dovrebbe fare**
Il check (credo si chiami così in gergo tecnico?) su che tipo di arma si è equipaggiata dovrebbe annullarsi dopo la morte, in modo che non capiti quanto prima descritto. Se si rilogga non dovrebbe dare l'arma persa con la morte.

**Screenshots (opzionale)** : //

**Comment by Lorenzo978** [comment]
Dovuto a non gestione del sistema morte.
