### ISSUE TITLE
[BUG] Anticheat & Armi

### ISSUE THREAD

**Issue by Rommel-theFox** [Lorenzo978/OC-issues#5]
**Descrizione**
Questo bug fa scattare l'anticheat quando si danno ad altri giocatori le stesse armi che hanno in mano ma con proiettili speciali diversi.
Mi spiego meglio:
Il **giocatore A** ha un M4 con 50 proiettili FMJ;
Il **giocatore B** ha un M4 con 50 proiettili HP;
Il **giocatore B** esegue con /dai il passaggio del suo M4 al giocatore A;
Il **giocatore A** avrà 100 proiettili FMJ e l'anticheat lo segnalerà.
Tale bug non si applica quando si danno armi di uno stesso tipo di proiettile speciale (FMJ con FMJ, HP con HP, JSP con JSP) o con uno stesso tipo di proiettile (Leggere con leggere). 

**Per riprodurlo**
//
**Cosa dovrebbe fare**
Se **A** ha un M4 con 50 proiettili FMJ e **B** gli passa un M4 con 50 proiettili HP, allora l'M4 con 50 proiettili FMJ di **A** andrà nell'inventario, in mano avrà invece l'M4 che gli ha passato **B** con i giusti proiettili.

**Screenshots (opzionale)** //

**Comment by Lorenzo978** [comment]
_Risolto in versione_ **0.3.1**
