### ISSUE TITLE
Bug /giveweapon

### ISSUE THREAD

**Issue by alepollo** [Lorenzo978/OC-issues#6]
**Descrizione**
Facendo per esempio: /giveweapon shotgun 10(colpi) **2(munizioni 00)**, per poi ripetere il CMD facendo /giveweapon shotgun colpi **3 (munizioni 000)** partirà l'anticheat (ADMIN ALERT) che si ripeterà ogni 3 secondi all'infinito. Se tu spari nell'intermezzo di quei 3 secondi tra a-a e a-a, ti ridarà le munizioni usate.

**Comment by Lorenzo978** [comment]
Quando si da un'arma già presente in mano ma con munizioni diverse queste vengono convertite con quelle presenti in mano al giocatore.
_Risolto in versione_ **0.4.1**
