### ISSUE TITLE
[MOD] Anticheat & spawn armi.

### ISSUE THREAD

**Issue by Rommel-theFox** [Lorenzo978/OC-issues#9]
Attualmente quando ci si spawna un'arma, seppure si è rilevati dall'anticheat, è possibile usarla per un breve lasso di tempo e fare un bel po' di danni. Bisognerebbe fare che non appena l'anticheat rileva un'arma spawnata, switcha automaticamente al pugno. (In caso il player slogghi e perda l'arma e chieda un risarcimento per un falso positivo, allora si provvederà a controllare le logs e rimborsarlo, quindi non c'è problema per quello).

**Comment by Lorenzo978** [comment]
_Risolto **(probabilmente)** nella versione_ **0.4.1**
